---
- hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml
  tasks:
  - name: Find the vm info
    vmware_vm_info:
      hostname: "{{ vmware_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      folder: "/{{ vmware_datacenter }}/{{ vmware_folder_type }}/{{ vmware_parent_folder }}/sadas"
      validate_certs: no
      show_attribute: yes
    register: vmware_vms
  - name: Print the Vmware details
    debug:
      var: vmware_vms
