---
- hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml
  tasks:
  - name: Move the Vms
    vmware_guest_move:
      hostname: "optimus.syslab.pnq2.redhat.com"
      username: "administrator@syslab.pnq2.redhat.com"
      password: "{{ vmware_password }}"
      datacenter: "Prime"
      validate_certs: no
      uuid:
      - "4200ad09-9d55-3ced-aef6-64f4ce9000b6"
      - "42004183-cab3-2701-e8ae-ddc918cf6eb1"
      dest_folder: "/Prime/vm/sysmgmt-pnq/saydas"
    delegate_to: localhost  
    register: vmware_vms
  - name: Print the Vmware details
    debug:
      var: vmware_vms
